# rename this to docker-compose.yml

version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    restart: unless-stopped
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf
    ports:
      - 2222:2222
    environment:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    depends_on:
      - zurg
    command: "serve sftp --no-auth --addr :2222 zurg: --retries 0 --low-level-retries 0"

volumes:
  zurgdata:
